version: '3'

services:
  postgres:
    image: postgres:latest
#    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FooDAppDiArYSeRVER
      POSTGRES_DB: uchet_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/db

volumes:
  postgres: